name: Push Docker containers to Docker Hub

on:
  workflow_dispatch: # For manual triggering
  release:
    types:
      - published

jobs:
  build:
    name: Build Docker containers
    runs-on: ubuntu-latest
    env:
      version: v1.0.3
    strategy:
      matrix:
        component: ["face-extractor", "speaker-identifier", "voice-extractor", "audio-transcriber", "sentiment-extractor"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build component from release tag
        uses: docker/build-push-action@v3
        if: github.event_name == 'release'
        with:
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
            branch=${{ github.event.release.tag_name }}
          context: ./docker/${{ matrix.component }}
          push: true
          no-cache: true
          tags: mexca/${{ matrix.component }}:${{env.version}}
      - name: Build component from main as 'latest' tag
        uses: docker/build-push-action@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
          context: ./docker/${{ matrix.component }}
          push: true
          no-cache: true
          tags: mexca/${{ matrix.component }}:latest
